name: update data.ts

on:
  schedule:
    - cron: "0 10 1 * *"
  # push:
  #   branches: [main]

jobs:
  run_script_and_update:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true
          fetch-depth: 0
          clean: true

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Run script
        run: |
          git config user.name "${{ secrets.MY_GITHUB_NAME }}"
          git config user.email "${{ secrets.MY_GITHUB_EMAIL }}"
          echo "-----------------------------------"
          echo $(npm -v)
          echo $(node -v)
          echo "-----------------------------------"
          wget --header="Authorization: token ${{ secrets.MY_TOKEN }}"  --no-check-certificate -O data_new.ts ${{ secrets.MY_REPO }}
          echo -e "\nexport { journal_abbr };\n\n\n" >> data_new.ts
          bash ./action_compare_file.sh
